<a href="https://colab.research.google.com/github/aitech-g5/pytorch_notebook/blob/main/prova_pytorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ogni tensore in pytorch ha delle proprietà come dtype,shape,device (dove il tensore è allocato)
import torch
tensor = torch.rand(3,4)
print(tensor)
print(f"Dimensione: {tensor.shape}")
print(f"Tipo di stato: {tensor.dtype}")
print(f"Dispositivo: {tensor.device}")

tensor([[0.6082, 0.3969, 0.6255, 0.9295],
        [0.6146, 0.9931, 0.0290, 0.3207],
        [0.8589, 0.5767, 0.3848, 0.9715]])
Dimensione: torch.Size([3, 4])
Tipo di stato: torch.float32
Dispositivo: cpu


In [ ]:
tensor2 = torch.arange(1,10).view(3,3)
print("Tensore originale:\n", tensor2)

Tensore originale:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
prima_colonna = tensor2[:,0]
print("\nPrima colonna: \n", prima_colonna)
tensor_ridimensionato = tensor2.view(1,9)
print("\nTensore ridimensionato (1x9):\n", tensor_ridimensionato)
tensor_trasposto = tensor2.t()
print("\nTensore traspoisto: \n", tensor_trasposto)


Prima colonna: 
 tensor([1, 4, 7])

Tensore ridimensionato (1x9):
 tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Tensore traspoisto: 
 tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


In [ ]:
# concatenazione e divisione
tensor_1 = torch.rand(2,3)
tensor_2 = torch.rand(2,3)

concatenated  = torch.cat([tensor_1,tensor_2], dim=0)
print("Tensori concatenati:\n", concatenated)
print("Dimensione dopo concatenazione:", concatenated.shape)

Tensori concatenati:
 tensor([[0.5683, 0.1802, 0.3867],
        [0.1678, 0.1557, 0.3339],
        [0.7931, 0.7914, 0.6505],
        [0.5020, 0.2213, 0.9568]])
Dimensione dopo concatenazione: torch.Size([4, 3])


In [ ]:
tensor = torch.rand(4,4)
split_tensor = torch.split(tensor,2)
print("\nTensori divisi:\n")
for i, t in enumerate(split_tensor):
   print(f"Parte {i+1}:\n", t)


Tensori divisi:

Parte 1:
 tensor([[0.0898, 0.3563, 0.3980, 0.0490],
        [0.3895, 0.8409, 0.1202, 0.8865]])
Parte 2:
 tensor([[0.1443, 0.2416, 0.4157, 0.4215],
        [0.7407, 0.0242, 0.6368, 0.9583]])
