<a href="https://colab.research.google.com/github/aitech-g5/pytorch_notebook/blob/main/operation_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
#operazioni aritmetiche con i tensor
import torch
tensor_a = torch.tensor([1,2,3])
tensor_b = torch.tensor([4,5,6])

#somma
add_result = tensor_a + tensor_b
print(add_result)
#sottrazione
sub_result = tensor_a - tensor_b
print(sub_result)
#moltiplicazione
mul_result = tensor_a * tensor_b
print(mul_result)
#divisione
div_result = tensor_a / tensor_b
print(div_result)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [28]:
# operazioni element-wise (potenza,trigonometria)
# operazioni di matrice come trasposizione
# operazione di broadcasting
tensor1 = torch.ones(3,1)
tensor2 = torch.ones(1,3)
print(tensor1,tensor2)
somma = tensor1 + tensor2
print(somma)



tensor([[1.],
        [1.],
        [1.]]) tensor([[1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [32]:
# operazione di riduzione (somme,medie,massimi,minimi) funzione di perdita delle reti neurali addestramento

tensor_a = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)

sum_result = torch.sum(tensor_a)
print(" Somma degli elementi del tensore:", sum_result)

mean_result = torch.mean(tensor_a)
print("\n Media degli elementi del tensore:", mean_result)

max_val, max_idx = torch.max(tensor_a, dim=0)
print("\n Valore massimo:", max_val)
print(" Posizione del valore massimo:", max_idx)
min_val, min_idx = torch.min(tensor_a, dim=0)
print("\n Valore mimimo:", min_val)
print(" Posizione del valore minimo:", min_idx)

max_pos = torch.argmax(tensor_a)
min_pos = torch.argmin(tensor_a)
print("\n Posizione del valore massimo con argmax", max_pos)
print("\n Posizione del valore minimo con argmin", min_pos)

 Somma degli elementi del tensore: tensor(15.)

 Media degli elementi del tensore: tensor(3.)

 Valore massimo: tensor(5.)
 Posizione del valore massimo: tensor(4)

 Valore mimimo: tensor(1.)
 Posizione del valore minimo: tensor(0)

 Posizione del valore massimo con argmax tensor(4)

 Posizione del valore minimo con argmin tensor(0)
