<a href="https://colab.research.google.com/github/aitech-g5/pytorch_notebook/blob/main/prova_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
# tensori in pytorch
# vettore
vector = torch.tensor([3,2])
print(vector)

tensor([3, 2])


In [2]:
print(vector.ndim)

1


In [3]:
print(vector.shape)

torch.Size([2])


In [4]:
# matrice - array multidimensionale
MATRIX = torch.tensor([[7,8],[9,10]])
print(MATRIX)

tensor([[ 7,  8],
        [ 9, 10]])


In [7]:
# tensore - array multidimensionale
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


In [8]:
zeros = torch.zeros((2,3))
print(zeros)
ones = torch.ones((3,3))
print(zeros)
random = torch.rand((2,2))
print(random)
zero_to_ten = torch.arange(start=0,end=10,step=1)
print(zero_to_ten)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.3143, 0.7598],
        [0.9041, 0.8497]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
